src/inter1/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("product.urls", namespace="product")),

]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

src/inter1/product/urls.py
from django.urls import path

from product import views

app_name = "product"
urlpatterns = [
     path("",views.index, name="index"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/",views.logout, name="logout"),



    path("product/add/", views.product_add, name="product_add"),
    path("product/delete/<int:id>/",views.product_del, name="product_del"),
    path("product/edit/<int:id>/", views.product_edit, name="product_edit"),

]

src/inter1/product/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="products")
    description = models.TextField()
    price = models.FloatField()

    class Meta:
        db_table = 'product_product'
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ('-id',)

    def __str__(self):
        return self.name
    

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'product_author'
        verbose_name = 'author'
        verbose_name_plural = 'author'
        ordering = ('-id',)

    def __str__(self):
        return self.user.username

src/inter1/product/views.py
from django.shortcuts import render,reverse
from django.shortcuts import HttpResponse
from django.http.response import HttpResponseRedirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required

from product.models import Product,Author

from django.contrib.auth.models import User

from product.form import ProductForm

@login_required(login_url='/login')
def index(request):
        products = Product.objects.all()

        context ={
            "title":"ECOMMERCE",
            "products":products
        }


        return render(request, "index.html", context=context)



def login(request):
     if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")


        if username and password:
                        user = authenticate(request, username=username, password=password)
                        if user is not None:
                            auth_login(request, user)

                            return HttpResponseRedirect(reverse("product:index"))
                        
                        else:
                            context ={
                                "title":"Login",
                                "error":True,
                                "message":"invalid credentials"
                            }

                        return render(request, "login.html", context=context)
            
        else:
            context ={
                "title":"Login",
            }
            return render(request, "login.html", context=context)
        
     else:
         context ={
                        "title":"Login",
                    }
         return render(request, "login.html", context=context)
         
        
  

def logout(request):
  
    auth_logout(request)

    return HttpResponseRedirect(reverse("product:login"))

def register(request):
    if request.method == 'POST':
       username = request.POST.get("username")
       first_name = request.POST.get("first_name")
       last_name = request.POST.get("last_name")
       password = request.POST.get("password")

       user = User.objects.create_user(
           username = username,
           first_name = first_name,
           last_name = last_name,
           password = password

       )

       user.save()

       author = Author.objects.create(
           user=user
       )

       author.save()

       return HttpResponseRedirect(reverse("product:login"))
    
    else:
       context={
           "title":"Create account",
       }
    
       return render(request, "register.html", context=context)
    
def product_add(request):
    if request.method == 'POST':
        form = ProductForm(request.POST,request.FILES,)
        if form.is_valid():
            instance =form.save(commit=False)
            instance.save()

            return HttpResponseRedirect(reverse("product:index"))
        
        else:
            pass


    else:
        form = ProductForm()
        context =  {
            "title": "product | index",
            "form":form
        }
        return render(request,"add_product.html", context=context)
    
def product_edit(request, id):
    instance = Product.objects.get(id=id)
    if request.method == "POST":
        form = ProductForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()

            return HttpResponseRedirect(reverse("product:index"))
        
        else:
            pass

    else:
        form = ProductForm(instance=instance)
        context={
            "title":" product | index",
            "form":form
        }

        return render(request, "add_product.html", context=context)
    
def product_del(request, id):
   products =Product.objects.get(id=id)
   products.delete()

   return HttpResponseRedirect(reverse("product:index"))

src/inter1/templates/add_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ecommerce</title>
    <link rel="stylesheet" href="{% static 'css/styel.css' %}">
</head>
<body>
    <section id="header">
        <section class="wrapper">
            <h1>
                <a href="">Ecommerce</a>
            </h1>
            <ul>
                <li><a href="">MANAGE PRODUCT</a></li>
                <li><a href="" class="btn">SIGN OUT</a></li>
            </ul>
        </section>
    </section> <!--header-end-->

<section id="category">
    <section class="wrapper">

        <h1>Table</h1>
        
     <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-controls">
            {{form.name}}
        </div> <br>
        <div class="form-controls">
            <label for="blog-image">Featured Image:</label>
            
            {{form.image}}
        </div> <br>
        <div class="form-controls">
            {{form.price}}
        </div> <br>
        <div class="form-controls">
            {{form.description}}
        </div><br>
        <div class="form-controls">
            <input type="submit" value="Add New" class="btn">
        </div>
     </form>
    </section>
  </section>

src/inter1/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ecommerce</title>
    <link rel="stylesheet" href="{% static 'css/styel.css' %}">
</head>
<body>
    <section id="header">
        <section class="wrapper">
            <h1>
                <a href="">Ecommerce</a>
            </h1>
            <ul>
                <li><a href="">MANAGE PRODUCT</a></li>
                <li><a href="{% url 'product:logout' %}" class="btn">SIGN OUT</a></li>
            </ul>
        </section>
    </section> <!--header-end-->

    <section id="home">
        <section class="wrapper">
            <h2>Manage Products</h2>
            <ul>
                <li><a href="">Home /</a></li>
                <li><a href="">Mnage Products</a></li>
            </ul>
        </section>
    </section><!--home-end-->
    
    <section id="spotlight">
        <section class="wrapper">
            <h2>  <a href="{% url 'product:product_add' %}">ADD</a></h2>
          
            <table border="1" width="100%">
                <thead>
                <tr>
                    <th>NAME</th>
                    <th>IMAGE</th>
                    <th>DISCRIPTION</th>
                    <th>PRICE</th>
                   
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr align="center">
                    <td>{{product.name}}</td>
                    <td><img src="{{product.image.url}}" alt="" width="100px"></td>
                    <td>{{product.description}}</td>
                    <td>{{product.price}}</td>
                    <td>
                        <a href="{% url 'product:product_edit' id=product.id%}" class="button">UPDATE</a>
                    </td>
                    <td>
                        <a href="{% url 'product:product_del' id=product.id%}" class="button">REMOVE</a>   
                    </td>
                </tr>
                {% endfor %}
            </tbody>
                
            </table>
        </section>
    </section>
</body>
</html>

src/inter1/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/styel.css' %}">
</head>
<body>
    <section id="login">
        <section class="wrapper">
            <div class="container">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="logo">
                        <img src="{% static 'images/logo.png' %}" alt="logo" />
                    </div>
                    <h1>Login Now</h1>
                    <div class="form-control" >
                        <input type="text" name="username" id="" placeholder="Enter username">
                    </div>
                    <div class="form-control">
                        <input type="password" name="password" id="" placeholder="Enter password">
                    </div>
                    <p>Don't have an account? <a href="{% url 'product:register' %}">Register</a></p>
                    <div class="btn">
                        <input type="submit" value="Login">
                    </div>
                </form>
                {% if error %}
                <p class="message">{{message}}</p>
                {% endif %}
            </div>
        </section>
    </section>
</body>
</html>

    

src/inter1/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
   {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <title>ecommerce</title>
    <link rel="stylesheet" href="{% static 'css/styel.css' %}">
</head>
<body>

    <section id="login">
        <section class="wrapper">
            <div class="container">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="logo">
                        <img src="{% static 'images/logo.png' %}" alt="logo" />
                    </div>
                    <h1>Create Account</h1>
                    <div class="form-control">
                        <input type="text" name="username" id="" placeholder="Enter username">
                    </div>
                    <div class="form-control">
                        <input type="text" name="first_name" id="" placeholder="Enter first name">
                    </div>
                    <div class="form-control">
                        <input type="text" name="last_name" id="" placeholder="Enter last name">
                    </div>
                    <div class="form-control">
                        <input type="password" name="password" id="" placeholder="Enter password">
                    </div>
                    <p>Already have an account? <a href="">Login</a></p>
                    <div class="btn">
                        <input type="submit" value="Register">
                    </div>
                </form>
            </div>
        </section>
    </section>
    
</body>
</html>